### ISSUE TITLE
Article Editor Backspace Problem

### ISSUE THREAD

**Issue by sganz** [pencilblue/pencilblue#719]
Hi, just loaded up PB on Mint  17.2 (Ubuntu). Trying it out on Firefox 40.0 and when I enter the rich text editor it seems that the back space does not work in WYSI edit mode. When in HTML or Mark Up mode  it seems to work OK.

Sandy

**Comment by blakecallens** [comment]
This should have been solved with #713. Are you running the latest version of the master branch?

**Comment by sganz** [comment]
Yes, I just did a git status and it shows branch is up to date with the Origin/Master. Nothing to pull. 0.4.1 Is the version in the admin.

**Comment by brianhyder** [comment]
@blakecallens I don't think you ever merged in PB713 (the branch that contained the fix).  The branch still exists.

**Comment by blakecallens** [comment]
Well, that would be a good reason why it's still broken.

**Comment by blakecallens** [comment]
Merged
